### ISSUE TITLE
Firefox Extension

### ISSUE THREAD

**Issue by shrpne** [minterscan/minter_link#1]
Please publish it to the Firefox store too.

Firefox Web Extensions support is almost the same as in Chrome so it should be easy

**Comment by whitesunset** [comment]
We're waiting for moderator approval :) Hope it will not take too long.

**Comment by shrpne** [comment]
Cool!

What about Safari? They added Web Extensions support recently. But I guess Apple Dev Certificate will be needed, which is pretty expensive (99$/year)

**Comment by whitesunset** [comment]
Thanks for advice, I will take a look on Safari extensions requirements and will try to run it locally. If it is not difficult, we will try to get through Apple moderation.

**Comment by whitesunset** [comment]
Now available for FF: https://addons.mozilla.org/en-GB/firefox/addon/minter-link/
